# Generated by Django 4.2.11 on 2024-03-12 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Refuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('petrol_type', models.CharField(choices=[('petrol95', 'petrol95'), ('petrol100', 'petrol100'), ('gas', 'gas'), ('diesel', 'diesel')], max_length=255)),
                ('amount', models.FloatField(default=0)),
                ('distance', models.IntegerField()),
                ('money', models.IntegerField()),
                ('gasstation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='refuels.gasstation')),
            ],
        ),
    ]
